### ISSUE TITLE
Exception: Null check operator used on a null value

### ISSUE THREAD

**Issue by MazenCoder** [ZEGOCLOUD/zego_uikit_prebuilt_live_audio_room_flutter#1]
### **When I click on the button "Take the seat" I got this issue, can you please help, Thanks!**

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
#0      ZegoSignalingPluginCoreInRoomAttributesData.setRoomAttributes (package:zego_uikit_signaling_plugin/src/core/in_room_attributes_data.dart:52:55)

#1      ZegoPluginInRoomAttributesService.setRoomAttributes (package:zego_uikit_signaling_plugin/src/service/in_room_attributes_plugin_service.dart:21:10)

### **--> roomID is null**
`result = await _zim!.setRoomAttributes(roomAttributes, _roomInfo!.roomID, config);`

**Comment by yoer** [comment]
Now the latest version has been updated, you can run our demo to see if there are any problems

https://github.com/ZEGOCLOUD/zego_uikit_prebuilt_live_audio_room_example_flutter/tree/master/live_audio_room

**Comment by yoer** [comment]
remember run 'pub get' to update the dependency to the latest release

**Comment by yoer** [comment]
1.0+ stable version had published

**Comment by yoer** [comment]
If you still report errors, maybe you haven't activate **[In-app Chat  Service](https://github.com/ZEGOCLOUD/zego_uikit_prebuilt_live_audio_room_flutter)** at **[ZegoClound Admin Console](https://console.zegocloud.com/)**
<img width="944" alt="wecom-temp-2ef8115a93966e040b6454b6142b6976" src="https://user-images.githubusercontent.com/11307627/208850680-aa909614-24f9-4ef3-83c3-712e228b0bf6.png">
