### ISSUE TITLE
How can i use onIMRecvBroadcastMessage 

### ISSUE THREAD

**Issue by digarahayu** [ZEGOCLOUD/zego_uikit_prebuilt_live_audio_room_flutter#2]
how to use onIMRecvBroadcastMessage when i use ZegoUIKitPrebuiltLiveAudioRoom. how i can trigger all event that available on ZegoExpressEngine

**Comment by yoer** [comment]
```dart

import 'package:zego_express_engine/zego_express_engine.dart';

void xx() {
  final expressEvent = ExpressEvent();

  ZegoUIKit().registerExpressEvent(expressEvent);
}

class ExpressEvent extends ZegoUIKitExpressEventInterface {
  @override
  void onIMRecvBroadcastMessage(
      String roomID, List<ZegoBroadcastMessageInfo> messageList) {
    // TODO: implement onIMRecvBroadcastMessage
    super.onIMRecvBroadcastMessage(roomID, messageList);
  }
}
```

**Comment by yoer** [comment]
You can inherit `ZegoUIKitExpressEventInterface` and listen to all event callbacks related to ZegoExpressEngine here

**Comment by digarahayu** [comment]
I can't find it in documentation 
Btw thanks ,finally it's works

**Comment by yoer** [comment]
[ZegoUIKitExpressEventInterface](https://pub.dev/documentation/zego_uikit_prebuilt_call/latest/zego_uikit_prebuilt_call/ZegoUIKitExpressEventInterface-class.html)

**Comment by Armysniper46** [comment]
hi how to use it im in the lost here

**Comment by yoer** [comment]
> hi how to use it im in the lost here
i'm sorry? what's your question?
