### ISSUE TITLE
Black Photo Appears Upon Entering Room

### ISSUE THREAD

**Issue by MohamedHassan1311** [ZEGOCLOUD/zego_uikit_prebuilt_live_audio_room_flutter#3]
When a user enters a room in the Flutter application, instead of the expected photo, a black image appears..
![Simulator Screenshot - iPhone 15 Pro - 2024-04-15 at 19 40 37](https://github.com/ZEGOCLOUD/zego_uikit_prebuilt_live_audio_room_flutter/assets/67841458/86f35478-37b5-43b8-af96-e3a8fe114b3c)

**Comment by yoer** [comment]
iOS virtual device? we don't support run in iOS virtual device
